### ISSUE TITLE
Fully dockerized local environment

### ISSUE THREAD

**Issue by Satendra-SR** [ProjectTides/tides#5]
As a developer, I would like use dockerized env for my local development.
- I should be able to spin up containers for both app and databases.
- I should be able to use `mix` command within the docker container.

**Comment by rathorevaibhav** [comment]
@Satendra-SR any update on this one? In-progress or complete?

**Comment by Satendra-SR** [comment]
@rathorevaibhav this can be closed now. The dockerized support for local env is available with https://github.com/ProjectTides/tides/pull/14 PR.
